# Generated by Django 4.0.1 on 2022-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_newuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
