# Generated by Django 4.0.1 on 2022-01-12 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('mention', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
